### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by alippai** [SyntaxC4-MSFT/PHP7Extension#2]
By turning on this extension the MySQL driver is lost.

**Comment by SyntaxC4** [comment]
You can modify the `php.ini` file in the `D:\home\SiteExtensions\PHP7Extension\Commands\PHP7x86` directory which will enable any extensions you want. 

Alternatively, you can follow the instructions on [Changing PHP_INI_SYSTEM configuration settings](https://azure.microsoft.com/en-us/documentation/articles/web-sites-php-configure/#_changing-phpinisystem-configuration-settings) which provides a `PHP_INI_SCAN_DIR` where you can place `.ini` files to change the system configuration.

> Note: In either of these scenarios above, you will need to restart your Web App for the changes to take effect.

**Comment by SyntaxC4** [comment]
Fixed in 0.0.9.
